const tenants = [
  {id:'zema',name:'ZEMA Demo Corp',instances:[
    {id:'sql-prod-01',name:'SQL-PROD-01',version:'SQL Server 2022',environment:'Production',health:'Warning',cpu:72,memory:81,storage:68,backup:'42 min ago',availability:'Synchronized'},
    {id:'sql-prod-02',name:'SQL-PROD-02',version:'SQL Server 2022',environment:'Production',health:'Healthy',cpu:34,memory:56,storage:44,backup:'37 min ago',availability:'Synchronized'},
    {id:'sql-dev-01',name:'SQL-DEV-01',version:'SQL Server 2019',environment:'Development',health:'Healthy',cpu:18,memory:41,storage:52,backup:'6 hr ago',availability:'Standalone'}],
   incidents:[
    {id:101,title:'Sustained CPU pressure',instance:'SQL-PROD-01',severity:'High',status:'Open',detected:'8 minutes ago',signal:'CPU exceeded 70% for 15 minutes',recommendation:'Review top Query Store regressions and wait statistics. Validate the plan before forcing any previous plan.'},
    {id:102,title:'Backup job duration anomaly',instance:'SQL-PROD-01',severity:'Medium',status:'Investigating',detected:'31 minutes ago',signal:'Full backup is 38% slower than its 14-day baseline',recommendation:'Check storage latency and concurrent maintenance activity. Do not cancel the active backup unless the recovery policy is protected.'},
    {id:103,title:'Failed login burst',instance:'SQL-PROD-02',severity:'Medium',status:'Open',detected:'2 hours ago',signal:'24 failed logins from one application identity',recommendation:'Confirm the application secret rotation and review the source host. Disable the login only after validating service impact.'}],
   findings:[
    {severity:'High',title:'SQL Agent proxy has excessive privileges',instance:'SQL-PROD-01',detail:'Proxy credential can access resources outside its required subsystem.'},
    {severity:'Medium',title:'Login auditing is not set to failed + successful',instance:'SQL-DEV-01',detail:'Current configuration records failed logins only.'},
    {severity:'Low',title:'SA login is enabled',instance:'SQL-PROD-02',detail:'The login is renamed and disabled access is recommended where policy permits.'}],
   capacity:[58,60,61,63,65,68,70,73,75,78,81,84]},
  {id:'northwind',name:'Northwind Field Services',instances:[
    {id:'nw-sql-01',name:'NW-SQL-01',version:'SQL Server 2022',environment:'Production',health:'Healthy',cpu:27,memory:48,storage:39,backup:'18 min ago',availability:'Standalone'}],
   incidents:[],findings:[{severity:'Low',title:'Password policy exception detected',instance:'NW-SQL-01',detail:'One SQL-authenticated service login does not enforce password policy.'}],capacity:[21,22,23,24,25,26,27,29,30,31,32,34]}
];

const state={tenantId:localStorage.getItem('zemaTenant')||tenants[0].id,view:'overview',selectedIncident:null};
const $=s=>document.querySelector(s); const tenant=()=>tenants.find(t=>t.id===state.tenantId)||tenants[0];
const statusClass=v=>v.toLowerCase();
const openIncidents=t=>t.incidents.filter(i=>i.status!=='Resolved');
function metric(label,value,note){return `<article class="metric"><p>${label}</p><strong>${value}</strong><small>${note}</small></article>`}
function instancesTable(items){return `<table><thead><tr><th>Instance</th><th>Environment</th><th>Health</th><th>CPU</th><th>Memory</th><th>Backup</th></tr></thead><tbody>${items.map(i=>`<tr><td><strong>${i.name}</strong><br><span class="muted">${i.version}</span></td><td>${i.environment}</td><td class="health ${statusClass(i.health)}">● ${i.health}</td><td>${i.cpu}%</td><td>${i.memory}%</td><td>${i.backup}</td></tr>`).join('')}</tbody></table>`}
function incidentsTable(items){if(!items.length)return '<div class="empty">No open incidents. All monitored systems are within policy.</div>';return `<table><thead><tr><th>Incident</th><th>Instance</th><th>Severity</th><th>Status</th><th>Detected</th></tr></thead><tbody>${items.map(i=>`<tr class="incident-row" data-incident="${i.id}"><td><strong>${i.title}</strong><br><span class="muted">INC-${i.id}</span></td><td>${i.instance}</td><td class="severity-${i.severity.toLowerCase()}">${i.severity}</td><td><span class="chip">${i.status}</span></td><td>${i.detected}</td></tr>`).join('')}</tbody></table>`}
function overview(t){const avg=(key)=>Math.round(t.instances.reduce((s,i)=>s+i[key],0)/t.instances.length);return `<div class="metric-grid">${metric('Monitored instances',t.instances.length,'Collector reporting normally')}${metric('Open incidents',openIncidents(t).length,openIncidents(t).filter(i=>i.severity==='High').length+' high priority')}${metric('Average CPU',avg('cpu')+'%','Across active instances')}${metric('Security score',(100-t.findings.length*8)+'/100','Based on demo policy')}</div><div class="content-grid"><article class="card"><div class="card-head"><h2>Instance health</h2><span class="muted">Last scan: just now</span></div>${instancesTable(t.instances)}</article><article class="card"><div class="card-head"><h2>Active incidents</h2><span class="chip">${openIncidents(t).length} open</span></div>${incidentsTable(openIncidents(t).slice(0,3))}</article></div>`}
function instances(t){return `<article class="card"><div class="card-head"><div><h2>Registered SQL Server instances</h2><span class="muted">Read-only telemetry collector</span></div><button class="secondary" disabled>+ Register instance</button></div>${instancesTable(t.instances)}</article>`}
function incidents(t){return `<article class="card"><div class="card-head"><div><h2>Incident queue</h2><span class="muted">Human approval required for remediation</span></div><span class="chip">${openIncidents(t).length} requiring attention</span></div>${incidentsTable(t.incidents)}</article>`}
function security(t){return `<div class="metric-grid">${metric('Security score',(100-t.findings.length*8)+'/100','Demo CIS-inspired checks')}${metric('High findings',t.findings.filter(f=>f.severity==='High').length,'Review immediately')}${metric('Checks passed',24-t.findings.length,'Latest policy scan')}${metric('Data collected','Metadata only','No business records')}</div><article class="card" style="margin-top:18px"><div class="card-head"><h2>Security findings</h2><span class="muted">Evidence-driven recommendations</span></div>${t.findings.length?t.findings.map(f=>`<div class="finding"><span class="severity-${f.severity.toLowerCase()}">${f.severity}</span><h3>${f.title}</h3><p>${f.instance} · ${f.detail}</p></div>`).join(''):'<div class="empty">No policy findings.</div>'}</article>`}
function capacity(t){const max=Math.max(...t.capacity)+8,points=t.capacity.map((v,i)=>`${20+i*(560/(t.capacity.length-1))},${150-(v/max*125)}`).join(' '),current=t.capacity.at(-1),growth=current-t.capacity[0];return `<div class="metric-grid">${metric('Storage used',current+'%','Primary production volume')}${metric('12-month growth','+'+growth+' pts','Synthetic forecast')}${metric('Projected threshold','11 months','At current growth rate')}${metric('Forecast confidence','87%','Demo model evaluation')}</div><div class="content-grid"><article class="card"><div class="card-head"><h2>Capacity forecast</h2><span class="muted">12-month projection</span></div><svg class="sparkline" viewBox="0 0 600 170" role="img" aria-label="Storage utilization forecast"><line class="grid" x1="20" y1="150" x2="580" y2="150"/><line class="grid" x1="20" y1="85" x2="580" y2="85"/><polyline points="${points}"/></svg></article><article class="card"><h2>Resource utilization</h2>${t.instances.map(i=>`<div class="bar-group"><div class="bar-label"><span>${i.name} storage</span><strong>${i.storage}%</strong></div><div class="bar"><span style="width:${i.storage}%"></span></div></div>`).join('')}</article></div>`}
const views={overview,instances,incidents,security,capacity};
const titles={overview:'Operations overview',instances:'SQL Server instances',incidents:'Incident response',security:'Security posture',capacity:'Capacity forecasting'};
function render(){const t=tenant();$('#pageTitle').textContent=titles[state.view];$('#content').innerHTML=views[state.view](t);$('#incidentBadge').textContent=openIncidents(t).length||'';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));document.querySelectorAll('[data-incident]').forEach(row=>row.addEventListener('click',()=>showIncident(Number(row.dataset.incident))));}
function showIncident(id){const i=tenant().incidents.find(x=>x.id===id);if(!i)return;state.selectedIncident=i;$('#dialogTitle').textContent=i.title;$('#dialogBody').innerHTML=`<dl class="detail-list"><dt>Incident</dt><dd>INC-${i.id}</dd><dt>SQL instance</dt><dd>${i.instance}</dd><dt>Severity</dt><dd class="severity-${i.severity.toLowerCase()}">${i.severity}</dd><dt>Status</dt><dd>${i.status}</dd><dt>Detection signal</dt><dd>${i.signal}</dd></dl><div class="recommendation"><strong>AI-assisted recommendation</strong><p>${i.recommendation}</p><small>Recommendation only—validate in the target environment before execution.</small></div>`;$('#resolveBtn').hidden=i.status==='Resolved';$('#incidentDialog').showModal();}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;render()}));
tenants.forEach(t=>$('#tenantSelect').add(new Option(t.name,t.id)));$('#tenantSelect').value=state.tenantId;$('#tenantSelect').addEventListener('change',e=>{state.tenantId=e.target.value;localStorage.setItem('zemaTenant',state.tenantId);render()});
$('#refreshBtn').addEventListener('click',()=>{const n=$('#scanNotice');n.textContent='Demo scan completed: telemetry refreshed, policy checks evaluated, and no automated changes executed.';n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),4500);render()});
$('#resolveBtn').addEventListener('click',()=>{if(state.selectedIncident)state.selectedIncident.status='Resolved';setTimeout(render)});
render();
